;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-semi&comma
        coffee-dedent-line-backspace
        electric-newline-and-maybe-indent
        go-mode-insert-and-indent
        kill-region
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-self-insert-command
        smarter-move-beginning-of-line
        sp-delete-char
        sp-forward-slurp-sexp
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        go-test-current-project
        mac-mwheel-scroll
        magit-status
        sgml-maybe-name-self
        sp-remove-active-pair-overlay
        ))
